### ISSUE TITLE
拆掉访问代理器之后预览位置绘制未停止

### ISSUE THREAD

**Issue by WildMeowGames** [shBLOCK/IntegratedProxy#1]
游戏版本：1.16.5
模组版本：1.0.2
forge版本：36.1.25

[BUG]
1、使用扳手拆掉访问代理器之后预览位置未停止绘制。
![image](https://user-images.githubusercontent.com/56909786/121362029-5ed91980-c968-11eb-9b8c-7bee16ba6b53.png)

2、变量卡在变量卡箱中时，变量卡箱被拆除后（指引用ID全部已丢失），访问代理器未能即时更新，依然保持运行。
3、再ID无任何丢失的情况下（使用扳手拆除的变量卡箱，内部变量卡ID全部无变化），重新放入变量卡箱后，访问代理器无法继续工作(显示器能正常显示该变量卡)。

![2](https://user-images.githubusercontent.com/56909786/121365584-5a623000-c96b-11eb-8eed-78fac0ec088d.jpg)
![3](https://user-images.githubusercontent.com/56909786/121365590-5c2bf380-c96b-11eb-817f-86aef68ec3c1.jpg)
![4](https://user-images.githubusercontent.com/56909786/121365599-5df5b700-c96b-11eb-9d06-04eb21390ff1.jpg)

4、在同位置，但所有变量卡和线路都拆掉（使用镐子挖掘）重做的情况下，访问代理器依然无法引用到变量卡（但在显示器中都能正常显示X和Z变量）。
![QQ图片20210609215417](https://user-images.githubusercontent.com/56909786/121368032-59ca9900-c96d-11eb-940e-3cc3adf38f6c.png)

最后：貌似找到原因了，在线缆连接处（网络与访问代理器）放了破坏口亦或者其他口的时候就脱离了网络，先全都拆掉再将破坏口放回去就可以正常工作，如果这个时候拿掉了一个变量卡，就又回到了第2条。

[建议]
希望在对应的代理期里有个能勾选隐藏位置框框的绘制，使用动态位置的时候闪瞎了QAQ，辛苦了！

**Comment by shBLOCK** [comment]
好的，感谢，我会尽快修复
还有，网络中无法找到变量的问题是因为要单独把代理器方块用线缆连接到网络里才行，拿其它东西对着是不算连接网络了的。
破坏重放显示正常其实是因为ID的一个线缆不会断开的bug。

**Comment by WildMeowGames** [comment]
感谢作者大大回复。
不过在动态联合原本的设备里面，都还是正常的属于同一个网络呢，像另一个附属NBT提取器就可以这样子做0.0。
这个访问代理器真是太棒了，可以实现特别多之前想要实现却又实现不了的装置！玩起来特别愉快，感谢付出！

**Comment by shBLOCK** [comment]
如果一个线缆是连接到代理器方块的情况下，这时候对着代理器方块的面放一个部件（读取器、写入器等等），这个线缆并不会与代理器断开，这个视频很直观

https://user-images.githubusercontent.com/50770712/121384844-3575b900-c97b-11eb-9468-c059e8bc0174.mp4

**Comment by shBLOCK** [comment]
暂时不关闭这个issue，因为扳手的那个问题还没有修复

**Comment by shBLOCK** [comment]
四个问题已经（大概）全部修复了（没太看懂第四个是什么意思，但是大概也是变量状态不会更新的问题，应该一起修复了），会很快在curseforge上发布

**Comment by shBLOCK** [comment]
Emm，先不关闭这个issue了，因为还没有弄关闭位置框的功能

**Comment by shBLOCK** [comment]
关闭渲染功能做好了，潜行右键来关闭渲染

**Comment by shBLOCK** [comment]
1.0.4版本以上可用

**Comment by WildMeowGames** [comment]
> 1.0.4版本以上可用

辛苦了！再次感谢，一直在使用，真是一个超级棒的MOD，我发誓我再也离不开它了。
