### ISSUE TITLE
Placing proxy on pre-existing interface or filtered interface breaks the proxy. (1.12/1.16)

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#10]
When connecting a proxy to a interface/filtered interface that is already placed, the proxy will break until a cable or other Integrated component is attached to it. In 1.12, the proxy doesn't say anything in the GUI until you add a cable to the original network. At which point the proxy will say no valid network. In 1.16, the proxy will say no valid network without having to cause any updates. Each time the error occurs, a null pointer exception is output in the log. Importers, exporters, readers and writers don't appear to have this issue.

[1.12](https://hastebin.com/efavuxugiy.properties)
[1.16](https://hastebin.com/lagovetogi.properties)

~~Easiest way to workaround this issue is to attach then remove a cable to the problematic proxy. Afterwards, it appears to work as expected.~~ Nevermind, you have to destroy the connected interface and reconnect it to get the proxy working correctly or connect the proxy directly to the network with cables. You can remove the added cables afterwards.
Example of how to reproduce in 1.12:
![2021-06-12_12 20 58](https://user-images.githubusercontent.com/997239/121784284-c4035980-cb78-11eb-827a-b2db90778f34.png)
![2021-06-12_12 20 55](https://user-images.githubusercontent.com/997239/121784283-c4035980-cb78-11eb-8bc8-a38fd213931e.png)
![2021-06-12_12 22 16](https://user-images.githubusercontent.com/997239/121784303-d8dfed00-cb78-11eb-9c1a-5fa57c8632cb.png)
![2021-06-12_12 21 06](https://user-images.githubusercontent.com/997239/121784285-c49bf000-cb78-11eb-83cc-91f9f74a12a5.png)
![2021-06-12_12 37 13](https://user-images.githubusercontent.com/997239/121784692-f746e800-cb7a-11eb-9a0b-c785acdeafb5.png)
![2021-06-12_12 37 49](https://user-images.githubusercontent.com/997239/121784704-0463d700-cb7b-11eb-8e39-0760151b7692.png)

**Comment by shBLOCK** [comment]
Wow, you are really trying anything aren't you, good job!
