### ISSUE TITLE
Proxy accepts items like an inventory when attached to existing item interface or filtered item interface on a network with item importers/exporters in 1.16

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#11]
Sorry for another report, but this issue seems to be 1.16 exclusive. Placing on existing interfaces seems to no longer cause crashes. However, in 1.16 it makes the proxy able to accept any item from an item importer when attached to an existing item interface/filtered item interface. Variables and items are also able to be pulled out of the proxy when connected to a chest with an item exporter. This only occurs when placing it on pre-existing interfaces, importers and exporters. This also occurs with world item importers and exporters. The same issue doesn't appear to occur the energy or fluid counterparts.

Workaround is to place proxy first then attach item interface, importer or exporter. There is not a workaround for world item importers or exporters though. They will always pull from or push to proxy inventory. There isn't a crash log and no info about it is in the regular logs.

Example:
![2021-06-12_19 15 13](https://user-images.githubusercontent.com/997239/121792374-97236680-cbb9-11eb-9ed8-01d32db551e2.png)
![2021-06-12_20 10 15](https://user-images.githubusercontent.com/997239/121792461-a22ac680-cbba-11eb-9701-a8729c250508.png)
![2021-06-12_19 15 15](https://user-images.githubusercontent.com/997239/121792375-97236680-cbb9-11eb-8ace-cc5711fbc769.png)
![2021-06-12_19 15 28](https://user-images.githubusercontent.com/997239/121792376-97bbfd00-cbb9-11eb-899d-0fae20787e63.png)
![2021-06-12_20 15 49](https://user-images.githubusercontent.com/997239/121792587-ab1c9780-cbbc-11eb-8c08-2c977d0ef14f.png)
![2021-06-12_20 18 35](https://user-images.githubusercontent.com/997239/121792588-ab1c9780-cbbc-11eb-91cc-e8bab80e5d72.png)

**Comment by shBLOCK** [comment]
Oh yep, I should disable the item access for proxy block
Thank for reporting

**Comment by Icoza** [comment]
Luckily once the proxy is full it works as intended, so I don't think the issue from 1.12 will be present but it's hard to say.

**Comment by shBLOCK** [comment]
I can disable the item interaction in TileEntity class in 1.12, but it was changed in 1.16, so I forget to add it back

**Comment by Icoza** [comment]
Yea, I'd imagine keeping tabs on what changed between MC versions is a pain.
