### ISSUE TITLE
World item importers and exporters don't work when proxy is attached to existing item interface in 1.12. Edit: Extends to item and energy interfaces, importers and exporters.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#12]
When attaching a proxy to an existing interface, most functionality seems to work now. The one issue I ran into was world item importers and exporters not working until you provide an update to the network by placing a cable or attaching another component in 1.12.

Integrated Proxy version: 1.12-1.0.8

Can be reproduced with a setup like this, then placing a proxy on the item interface and have it point to the chest. No items will be picked up or dropped into the world until you add a cable to the network.
![2021-06-12_20 35 26](https://user-images.githubusercontent.com/997239/121792683-c9cf5e00-cbbd-11eb-80c5-9963be6d1139.png)

Luckily in this case, the workaround is just to cause an update to the Dynamics network.

Edit: Workaround still seems to remain, but the issue happens whenever the proxy is placed on an item interface. Will update with images and better explanation before I go to sleep later. I can't appear to get the issue to happen with fluid interfaces and fluid components, but it's hard to tell.

**Comment by shBLOCK** [comment]
Thank for reporting!

**Comment by Icoza** [comment]
I'm sorry lol, I wasn't trying to find anymore issues today. This just popped up after I got my hands on the fixed interface update and tried to use it in a build.

**Comment by Icoza** [comment]
https://user-images.githubusercontent.com/997239/121795298-15d9cd00-cbd5-11eb-900a-b8647005f165.mp4

I think I'm getting closer to guessing the cause. It seems as though when a proxy is placed or broken on an interface of any kind, the Dynamics network doesn't get updated.

**Comment by shBLOCK** [comment]
Yep, you can try it with IntegratedTerminals
Sorry for being late, I was doing my homework

**Comment by Icoza** [comment]
That is with tunnels I believe and in 1.12. No worries, I still want to mess around with the item and energy interface because I think the energy network doesn't work even if you put the importer or exporter on the proxy. Got busy so I can't record any videos or test for another hour and a half or so. Take care of what you need to first though, homework is more important.

**Comment by Icoza** [comment]
I couldn't think of how to describe it through text concisely so I got the recording software out.

**Comment by shBLOCK** [comment]
I mean you can use the terminal to see the item/fluid/energy content of the network, you can see when you change the target of the proxy block, the content in the terminal doesn't change

**Comment by Icoza** [comment]
Ahh, I'll have to try that and see if placing/breaking a proxy on an interface updates the amounts. It'll be a second though because something came up, sorry about that.

**Comment by Icoza** [comment]
Would it be possible to call a Dynamics network updating when placing or destroying a proxy?

**Comment by shBLOCK** [comment]
Yep, I'm finding that function or event or something

**Comment by Icoza** [comment]
Sounds good, I'll do some more tests but in my layman's observations, updating the network with a cable seems to work but I haven't messed with it enough. :cry:

**Comment by shBLOCK** [comment]
Ugh, I was think of this sooooooooooooo complex, I even tried add a Mixin...
But in the end I added 3 lines of code to solve it...

**Comment by Icoza** [comment]
I'm sorry to hear about that. Luckily it's only 3 lines of code in the end which means less stuff to break. I did run into one reproducible issue, but I think you'll just have to use the same code on block destruction. I'll post an issue for it.

**Comment by Icoza** [comment]
Sorry to bother, but this issue is also reproducible in 1.16.

https://user-images.githubusercontent.com/997239/121801341-77616200-cbfc-11eb-973f-fc6217f81ce4.mp4
