### ISSUE TITLE
Proxy connection remains after breaking block. (1.12) and #12 occurs in 1.16

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#13]
The update fixed placing a proxy on an existing interface, but the network is not updated upon breaking the proxy. I might suggest changing the network update call to when a proxy is placed or destroyed instead of changing proxy target. I believe that would solve #12 as well as this. Hopefully the fix is adding the 3 lines of code from #12 to when proxy is placed and broken.

Workaround is to update the network with a cable.

I was able to reproduce #12 in 1.16, but unable to currently reproduce this issue. 

Example:
https://user-images.githubusercontent.com/997239/121802036-1dfb3200-cc00-11eb-80bb-44560f1d6090.mp4
https://user-images.githubusercontent.com/997239/121802058-39fed380-cc00-11eb-914d-ca23b0a4cdd2.mp4
https://user-images.githubusercontent.com/997239/121802071-5569de80-cc00-11eb-923e-68a4c5d49e3b.mp4
https://user-images.githubusercontent.com/997239/121802230-fb1d4d80-cc00-11eb-9f79-121359492d44.mp4

Edit: #12 occurring in 1.16:
https://user-images.githubusercontent.com/997239/121802396-afb76f00-cc01-11eb-9ac9-72ff08222a0b.mp4

**Comment by shBLOCK** [comment]
Thank for reporting, sorry for being late

**Comment by Icoza** [comment]
No need to apologize at all. Sorry I keep postings more issues. I just saw the update and couldn't stop myself. You're making great progress.

**Comment by shBLOCK** [comment]
I couldn't stop make this mod better with you as well!

**Comment by Icoza** [comment]
😄

**Comment by shBLOCK** [comment]
Still working on fix this in 1.16 though

**Comment by Icoza** [comment]
I'm guessing Dynamic networks function and update differently in 1.16 compared to 1.12?
