### ISSUE TITLE
Redstone writer attached to proxy causes lag and log spam.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#14]
This only appears to affect the redstone writer and I believe I tracked the issue down to c6618214d25bc9ff1f2cad035c28e61067658707. This bug is not present in version 1.0.8 which is why I believe the redstone writer is acting strange with that commit. Every other reader, writer and interface appears to interact correctly. The order of connection doesn't appear to matter, if you insert a variable into a redstone writer that is pointing towards a proxy, the log spam starts.

[Log](https://hastebin.com/imacudafik.sql) with the different errors separated by '/'.

**Comment by Icoza** [comment]
Why does the redstone writer always have to be a pain.

**Comment by shBLOCK** [comment]
Ok, thank for reporting

**Comment by Icoza** [comment]
I'm sorry, I tried to make some changes to the code to see if I could do anything. That didn't go very well.

**Comment by shBLOCK** [comment]
This is actually a very bad issue, hopefully it didn't break your world

**Comment by Icoza** [comment]
Oh dang, I haven't updated my main server to this change. I am running into an issue on trying to update the mod though. I think I have to break the block before updating but I'm not sure. I'll post crash log here in a sec unless I should make it a new issue.

**Comment by shBLOCK** [comment]
Remember to backup your world before update the mod, this mod is still not stable enough
