### ISSUE TITLE
本地服务器突然开不起了...

### ISSUE THREAD

**Issue by hanxiaoxin778** [shBLOCK/IntegratedProxy#15]
游戏版本:1.16.5
MOD版本:1.0.8

`---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 6/14/21 3:57 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.shblock.integratedproxy.tileentity.TileAccessProxy.onTargetChanged(TileAccessProxy.java:470) ~[integrated_proxy:1.0.8] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_382_TileAccessProxy_onTargetChanged_NeighborNotifyEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:172) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_195593_d(MixinWorldRedstone.java:292) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:A,pl:runtimedistcleaner:A}
	at me.desht.modularrouters.block.tile.TileEntityItemRouter.compile(TileEntityItemRouter.java:529) ~[modularrouters:task ':jar' property 'archiveVersion'] {re:classloading}
	at me.desht.modularrouters.block.tile.TileEntityItemRouter.func_73660_a(TileEntityItemRouter.java:310) ~[modularrouters:task ':jar' property 'archiveVersion'] {re:classloading}
	at net.minecraft.world.World.func_217391_K(MixinWorldRedstone.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251] {}`

在服务器启动完毕之后的一瞬间，服务器报这个错然后重启
还记得一点，在上次关服之前，我做了一个挖矿的装置，按顺序 X:[0-512]  Y：[1-40]  Z:[0-512] 挖掘方块。
除了这一点没有其他信息可提供的了QAQ

**Comment by shBLOCK** [comment]
好的，非常抱歉，现在版本降到1.0.7应该能暂时修复

**Comment by shBLOCK** [comment]
[我不太确定这个问题的原因是什么，所以麻烦用这个版本运行一下服务器，然后发一下日志
https://www.curseforge.com/minecraft/mc-mods/integrated-proxy/files/3350908

**Comment by shBLOCK** [comment]
运行之前记得备份存档！

**Comment by hanxiaoxin778** [comment]
> [我不太确定这个问题的原因是什么，所以麻烦用这个版本运行一下服务器，然后发一下日志
> https://www.curseforge.com/minecraft/mc-mods/integrated-proxy/files/3350908

我这边已经测试不了了QAQ ，之前为了早点开服，就先把IntegratedProxy删掉了，然后使用其他方块覆盖并拆除了区块上的代理器方块原来的位置。最后重新把IntegratedProxy装回来了... 当时小伙伴们都在等着要玩，就只能这样处理了，只有我一个人在使用访问代理期。。。  (虽然所有装置都坏了T_T

**Comment by hanxiaoxin778** [comment]
> 运行之前记得备份存档！

只有等我重新做了些装置之后再重启看看能不能复现

**Comment by shBLOCK** [comment]
额，非常抱歉...

**Comment by shBLOCK** [comment]
建议装一个FTB Backup模组，自动备份存档

**Comment by hanxiaoxin778** [comment]
> 额，非常抱歉...

没关系的没关系的，因为它(IntegratedProxy)的存在，让我做到了很多以前做不到的事情，因为它的存在已经变的更美丽了！我喜欢它

**Comment by hanxiaoxin778** [comment]
> 建议装一个FTB Backup模组，自动备份存档

存档太大了，使用这个硬盘很快就.....  因为我使用ChunkPregenerator提前加载各个世界区块的，地图文件有16G多....QAQ

**Comment by shBLOCK** [comment]
配置文件中可以设置备份文件夹总大小上限，超过会删除一个最老的备份

**Comment by hanxiaoxin778** [comment]
> 配置文件中可以设置备份文件夹总大小上限，超过会删除一个最老的备份

嗯嗯，好的，感谢！我即刻用起来。
还有另一件事，想请教一下您。

就是我一直在做游戏开发（Unity & Cocos），然后也玩了10多年MC了，以前（几年前）也写过一些小MOD，但没有正式（按照规范）的写过，只是粗略的了解过各方面的知识，如果有需要的话我会去补习。

因为特别喜欢动态联合这个MOD，我也想写一个附属，功能：

多方块结构的显示器
拷贝整个网络
快速清除变量卡信息
快速定义变量卡
快速复制变量卡
快速修改变量卡
按指定范围指定频率随机数变量卡（需要方块辅助计算——设值器） //集成动力原版读取器（因为有访问代理器的存在
按指定范围指定频率递增的变量卡（需要方块辅助计算——设值器） //集成动力原版读取器（因为有访问代理器的存在
按指令列表指定频率变化的变量卡（需要方块辅助计算——设值器） //使用集成动力读取器（因为有访问代理器的存在
快速创建方块坐标的3张变量卡（需要读取方块——坐标提取器）//（因为有访问代理器的存在

可是在第一步就卡住了，尝试添加动态联合所有MOD的deobf依赖后，启动MC就(尝试过各种姿势...
![image](https://user-images.githubusercontent.com/56909786/121823957-2d02e280-ccdb-11eb-9c0f-6a7ae7da6b54.png)

更换了不同版本的动态联合MOD也都是这样..

然后我克隆了你IntegratedProxy的仓库下来，发现是1.12.2的... 因为现在正在玩1.16.5，所以想先做高版本的QAQ

所以我想跟你要一份1.16.5的工程，用来学习&借鉴一下...  （想照葫芦画瓢

**Comment by shBLOCK** [comment]
这个我也遇到过，最后解决方法很简单粗暴
如果是用git clone 指令克隆的化是可以切换分支的，百度上搜一下就知道了（check out)
或者我现在把1.16设置为默认分支，这样你克隆的就直接是1.16了

**Comment by shBLOCK** [comment]
![chrome_7YthLRZ1v1](https://user-images.githubusercontent.com/50770712/121824132-68ea7780-ccdc-11eb-851e-e186e1035537.png)
其实不需要，在github网页上可以直接下载

**Comment by hanxiaoxin778** [comment]
> ![chrome_7YthLRZ1v1](https://user-images.githubusercontent.com/50770712/121824132-68ea7780-ccdc-11eb-851e-e186e1035537.png)
> 其实不需要，在github网页上可以直接下载

嗯嗯，非常感谢，已经下载下来了！

**Comment by hanxiaoxin778** [comment]
是的，又出现了，这个只要是用了代理器之后重启的话就开不起来，我现在去装debug版本看看

**Comment by hanxiaoxin778** [comment]
不好意思，我之前忘记下载debug版了，现在链接已经失效了QAQ

**Comment by hanxiaoxin778** [comment]
我本地保存了一份有开不了服的存档，我先用1.0.7的让服务器跑起来，等你明天重新上传一下debug版，我再去测试一下拿日志文件给你，麻烦啦~

**Comment by hanxiaoxin778** [comment]
at com.shblock.integratedproxy.tileentity.TileAccessProxy.onTargetChanged(TileAccessProxy.java:456) ~[integrated_proxy:1.0.7] {re:mixin,re:classloading}

1.0.7也不行呢

**Comment by shBLOCK** [comment]
1.12的版本已经到1.0.13了，上次有另一个discord上的也遇到这个问题了，他更新到1.0.13就好了

**Comment by hanxiaoxin778** [comment]
哦哦，我是1.16.5的

**Comment by hanxiaoxin778** [comment]
我看了一下1.16.5的没更新来着.

**Comment by shBLOCK** [comment]
1.16到1.0.14了
https://www.curseforge.com/minecraft/mc-mods/integrated-proxy/files/3351042
这个版本保留了日志输出，可以替代debug版

**Comment by hanxiaoxin778** [comment]
好的，我现在用的就是1.0.14版本，我去有问题的存档里跑一下看看

**Comment by hanxiaoxin778** [comment]
本地的存档下来又没问题了，那我先使用1.0.14吧，我晚点刻意去做一个装置，然后重启试试

**Comment by shBLOCK** [comment]
好的，因为已经加了错误捕捉，所以不会报错了，但是会输出日志
如果真的是那一个问题的化，应该不会再崩了

**Comment by shBLOCK** [comment]
先关闭这个issue，如果有新的问题可以再打开

**Comment by hanxiaoxin778** [comment]
![9~T($S L@RUB{R{3N}BQMQM](https://user-images.githubusercontent.com/56909786/122359053-cd7d2f00-cf87-11eb-8634-bd8889d7ca38.png)
你好shBLOCK... 我说的那个MOD写了一半了,现在想跟IntegratedProxy有个联动，就是有一个叫“坐标提取器”的东西，只有在安装了 IntegratedProxy 之后才会有（毕竟坐标提取器没别的作用了....），可是发现用JitPack拉不到1.16的项目，会提示错误，还有版本号都不是可读的，分不清版本...

**Comment by hanxiaoxin778** [comment]
哦对了还有一个BUG，我直接在这里提一下算了，不去开issue了， 就是很多个代理器在同一个网络的时候会频繁发生停止工作的情况，把变量卡拿出来再塞回去就回复了正常，但旁边的其他代理器就停止工作了，对其他代理器执行相同的操作之后，先前的那台就又停止了。
![8BFEJUY4_AK}HLRQEO$NXM6](https://user-images.githubusercontent.com/56909786/122360054-ad9a3b00-cf88-11eb-8e9a-f98ee91dbdbe.jpg)

**Comment by shBLOCK** [comment]
最简单的办法是直接下载curseforge上的mod文件，然后用idea可以直接当错ExternalLibrarys加进去（具体百度搜一下就有

**Comment by hanxiaoxin778** [comment]
FORGE的开发环境能运行混淆后的MOD么0.0 不是说1.13之后已经不支持了吗

**Comment by shBLOCK** [comment]
可以的（可能前置mod版本和mappings要一样），我也在弄一个mod把这个当前置，已经试过了
而且curse上的没混淆

**Comment by shBLOCK** [comment]
对了，坐标提取器的意思是要方便提取XYZ变量卡吗？

**Comment by hanxiaoxin778** [comment]
嗯好的，混淆表我用的也是20201028那个1.16.3的，我之前用了最新的混淆表发现好多方法都改名/不在了，到时候升1.17会不会很难受.

是的，用提取器shift+右键指定方块之后，再shift+右键 访问代理器，会主动消耗掉3张空白变量卡赋值并输入到访问代理器里面。

**Comment by hanxiaoxin778** [comment]
那个..  再打扰一下，我弄了挺久了，就是添加到库之后，能引用到相关类了，但开发环境加载不了非deobf的MOD... 我没法同步测试QAQ，写好了要编译去正式环境才能测特别慢.... 还有上边那个BUG...

**Comment by hanxiaoxin778** [comment]
你好shBLOCK，再次打扰一下。。 就是IntegratedProxy你之后还准备更新的吗，这个模组确实挺好用已经离不开了，如果你不准备更新了话我想接坑并添加到[Integrated Additions](https://www.curseforge.com/minecraft/mc-mods/integrated-additions)里面去...  QAQ

**Comment by hanxiaoxin778** [comment]
> 会继续更新的，最近要期末考试+学业考试，放假后会继续更新

好的没问题！

**Comment by shBLOCK** [comment]
今天正好有点时间，把剩下两个issue修了，上面提到的网络失效问题（可能）会明后天修复

**Comment by hanxiaoxin778** [comment]
> 今天正好有点时间，把剩下两个issue修了，上面提到的网络失效问题（可能）会明后天修复

辛苦了啦，好像现在那种记录方块信息然后做渲染的方式不太行，容易出现在方块实际已经消失了之后，还存在的情况，并不一定会触发BlockDestroy事件....

**Comment by hanxiaoxin778** [comment]
还有那个你...curse 链接能不能挂一下[Integrated Additions](https://www.curseforge.com/minecraft/mc-mods/integrated-additions)跳转QAQ

**Comment by shBLOCK** [comment]
好的
![chrome_o2z6GbYUhY](https://user-images.githubusercontent.com/50770712/123078518-a45c1300-d44d-11eb-9390-9f36f5b9bd01.png)

**Comment by shBLOCK** [comment]
> > 今天正好有点时间，把剩下两个issue修了，上面提到的网络失效问题（可能）会明后天修复
> 
> 辛苦了啦，好像现在那种记录方块信息然后做渲染的方式不太行，容易出现在方块实际已经消失了之后，还存在的情况，并不一定会触发BlockDestroy事件....

你什么更好的方法吗？不太可能扫描整个世界来找代理器，而且如果代理器本身在客户端加载范围之外也不会显示

**Comment by hanxiaoxin778** [comment]
实际上那个动态数值读取器也是为访问代理器做的QAQ 原版集成动力几乎用不到，这个可以省下大量的变量卡，正常情况，世界时间%然后+，等等一系列，用这个的话一个变量卡就可以搞定了

**Comment by hanxiaoxin778** [comment]
我那个巨型显示器用的是集成动力包装的，TileEntityRenderer渲染的

**Comment by hanxiaoxin778** [comment]
由TitleEntity本身驱动的渲染更新就肯定不会有问题了吧QAQ ，我也还没用到，不过我接下来写的蓝图拷贝器也是整方块，需要渲染的，我还没开始做，不过做的话肯定这样做了

**Comment by hanxiaoxin778** [comment]
不过我也才接触没多久，基本全靠看MC源码和按集成动力思路来走的。开始mixin部分我都想用反射的，因为觉得以前coremod麻烦，然后去到处看了看资料发现有mixin的存在，就用上了...    我是需要用到了才去看的，所以我说的也不一定是对的Orz

**Comment by shBLOCK** [comment]
用TE的渲染的化也是那个问题，不在客户端加载范围内的化就不会渲染，所以如果要指向一个非常远的地方就会看不到

**Comment by shBLOCK** [comment]
刚接触两周做这么大个模组也是真厉害，自愧不如...

**Comment by hanxiaoxin778** [comment]
我主入口类和mods.toml都是直接拷贝你的！那也占你的光哈哈哈.
哦我懂了，你的意思是指向一个很远的地方时候，TE方块已经不存在客户端中了，客户端就自然看不到指定目标位置了是吧。

那这样你看可不可行,
服务端tileEntity tick里做发包(当前访问代理器绑定的目标位置-)给客户端1秒1次,客户端根据距离来决定在不在worldlastrenderer里渲不渲染.
这样就能保证tileEntity确实存在世界中并更新了，如果不存在了tick也不走了。

**Comment by shBLOCK** [comment]
服务端不加载肯定不需要渲染
一秒发一次如果感觉有点慢，每tick一次又比较消耗流量
我再想想办法吧

**Comment by hanxiaoxin778** [comment]
> 服务端不加载肯定不需要渲染
> 一秒发一次如果感觉有点慢，每tick一次又比较消耗流量
> 我再想想办法吧

客户端每次接到消息之后默认渲染2秒，2秒后渲染状态停止(考虑下一次包到来的延迟问题，导致状态没有继续保持而中间出现闪烁)，如果收到了继续保持渲染2秒，这个状态更新慢1-2秒我认为一点问题也没有QAQ

**Comment by shBLOCK** [comment]
基本是把所有能找到的方块破坏方法加上事件都用了，不管有没有用...

**Comment by hanxiaoxin778** [comment]
> 基本是把所有能找到的方块破坏方法加上事件都用了，不管有没有用...

嗯看到了的，我也去看看有没有好的办法。

**Comment by hanxiaoxin778** [comment]
还有个问题想向你了解一下，就是我给 实体写入器 加了 传送实体的功能，一开始我加了在配置里改范围的功能，后来发现集成动力的接口参数输入校验是在本地做的，不需要通过服务端验证的，可以直接反编译字节码去掉参数限制，如果是服务端，int类型直接传字符就可以让服务器崩溃，在服务端最终处理逻辑那里做范围判断然后发消息给玩家似乎不太妥当，所以我就直接删掉了配置文件。

后来仔细想了想，使用集成动力应该大部分都是局域网&单机玩家，并不会有像商业服那样的服务器会安装吧？毕竟也无法去考虑权限问题，也没太大必要。所以我觉得像访问代理器啊，传送器之类的加不加验证似乎也没太大必要，单机玩家觉得不破坏平衡就行了对不对QAQ，我再加这个功能之前询问过kroeser，他说挺酷... 

所以我不确定为集成动力添加一些这样比较OP的功能合不合适....以后加东西需不需要考虑到这一层(植物魔法 作者似乎不太喜欢 额外植物学)。还有访问代理器也是，不过虽然你也加了配置但我没去改，然后特大的范围挖矿（我测试过，在有区块文件，但区块没被加载的情况下，破坏口也能工作，似乎破坏口在破坏目标方块的时候会加载该区块，我也没去仔细看）或者其他的一些操作，就觉得不太平衡，给别人用的话。

**Comment by shBLOCK** [comment]
在我看来：集成动力已经够OP了，合成那么简单的接口可以做到基本无限的传输速度，如果有别人认为太OP可以改配置文件，整合包作者可以改合成等等（很多整合包最后不是都可以做出各种创造物品吗）
模组也只是提供功能，具体平衡性需要整合包作者去自己调节（无尽贪婪那么OP不是很多整合包里都有吗）
破坏口确实又可能去加载区块，加载范围之外应该只有红石的东西不能用（之前发现太卡就禁止了）

这方面应该没必要太担心

**Comment by shBLOCK** [comment]
但是配置文件还是加上好，毕竟有人故意研究一个对于参数作弊的东西的几率太低了

**Comment by hanxiaoxin778** [comment]
> 但是配置文件还是加上好，毕竟有人故意研究一个对于参数作弊的东西的几率太低了

嗯，那我就不想那么多了，就按自己的想法来做一些好玩的东西出来√， 不过接口参数这个感觉不管怎么处理都不妥当，因为服务器改了没用的，参数的配置只能由客户端决定的，客户端改多少就范围是多少，最终接受参数的地方是在客户端，服务器不走验证方法的。 hhhh

**Comment by shBLOCK** [comment]
emm，接口参数到底指什么，不是说配置文件吗？配置文件不是在服务端的吗？

**Comment by hanxiaoxin778** [comment]
![QQ截图20210623202516](https://user-images.githubusercontent.com/56909786/123095950-2dc91080-d461-11eb-92a5-62a321753e02.jpg)

这个，读取器和写入器的参数，哈哈哈，这个是在客户端校验的，也就是说这个ID，可以强制传一个String过去，那样服务器就直接报错重启了。这个校验方法只在客户端执行

**Comment by shBLOCK** [comment]
哦，懂了，但是这个参数和范围配置文件又什么关系呢？很抱歉没有看懂你的意思

**Comment by hanxiaoxin778** [comment]
哦，就是写入器和读取器只能在这个地方做数据校验，然后实体写入器里面的传送实体是在这里设置X Y Z 位置的

**Comment by shBLOCK** [comment]
哦，其实我认为更好的方式是做成动态的变量？比如可以传入一个列表类型的变量，其中有三个int值代表XYZ

**Comment by hanxiaoxin778** [comment]
> 哦，其实我认为更好的方式是做成动态的变量？比如可以传入一个列表类型的变量，其中有三个int值代表XYZ


他每个功能对应一个槽，如果是传入List的话，这个和集成动力原本的设计就不太一样了，在原版的读取器写入器里没有这种相关的操作，这种比较迷糊。因为他这里的设计比较独特，他在开发文档中强调独立开来，处理和输入全泛型强制解耦的。等下次如果你要做读取器or写入器的时候就会发现这个问题了QAQ
![QQ截图20210623203049](https://user-images.githubusercontent.com/56909786/123096660-e98a4000-d461-11eb-9a59-6df427a78a0d.jpg)

**Comment by shBLOCK** [comment]
那就没办法了，我还有两个个人想法：
要不弄一个专门的传送器方块，可以读取多个变量，但是模组得大改
或者是用一个Long类型代表坐标（BlockPos类中能找到toLong()和fromLong()），但是有点太麻烦了
感觉都不太靠谱，也只是个人意见

**Comment by hanxiaoxin778** [comment]
> 那就没办法了，我还有两个个人想法：
> 要不弄一个专门的传送器方块，可以读取多个变量，但是模组得大改
> 或者是用一个Long类型代表坐标（BlockPos类中能找到toLong()和fromLong()），但是有点太麻烦了
> 感觉都不太靠谱，也只是个人意见

对，开始我准备做成独立方块的，像访问代理器这样，插如实体+X+Y+Z，但之前玩的时候发现部分看名字就比较OP的写入器，如 实体写入器、机器写入器、容器写入器，这种显示 警告：要安装其他MOD才能生效，然后我到处找了看也没发现集成动力有附属...... 刚好之前做这个功能， 就想着作者只做了这个写入器但没加入功能就是等着附属来加的... 所以我看了一下，刚好和实体写入器比较匹配，写入坐标嘛~  就加进去了， 传送器这个地方的代码量不多，还没我那个数值读取器一半多23333。是可以考虑的，先放着就这样先。目前在做蓝图拷贝整个网络这里比较麻烦，ID的分配和关联，还有网络的重建，要仔细参悟集成动力的网络设计然后列个文档，一一的去考虑可能发生的事情，hhhh不然会容易出BUG。

对了可不可以要个联系方式，比如企鹅什么的，在你有空的时候并且有意愿的话也可以聊聊这方面的。

**Comment by hanxiaoxin778** [comment]
不方便没关系的哈哈哈，那就先这样了，考试加油！

**Comment by shBLOCK** [comment]
你有Discord账号吗？QQ一般不在线

**Comment by shBLOCK** [comment]
> > 那就没办法了，我还有两个个人想法：
> > 要不弄一个专门的传送器方块，可以读取多个变量，但是模组得大改
> > 或者是用一个Long类型代表坐标（BlockPos类中能找到toLong()和fromLong()），但是有点太麻烦了
> > 感觉都不太靠谱，也只是个人意见
> 
> 对，开始我准备做成独立方块的，像访问代理器这样，插如实体+X+Y+Z，但之前玩的时候发现部分看名字就比较OP的写入器，如 实体写入器、机器写入器、容器写入器，这种显示 警告：要安装其他MOD才能生效，然后我到处找了看也没发现集成动力有附属...... 刚好之前做这个功能， 就想着作者只做了这个写入器但没加入功能就是等着附属来加的... 所以我看了一下，刚好和实体写入器比较匹配，写入坐标嘛~ 就加进去了， 传送器这个地方的代码量不多，还没我那个数值读取器一半多23333。是可以考虑的，先放着就这样先。目前在做蓝图拷贝整个网络这里比较麻烦，ID的分配和关联，还有网络的重建，要仔细参悟集成动力的网络设计然后列个文档，一一的去考虑可能发生的事情，hhhh不然会容易出BUG。
> 
> 对了可不可以要个联系方式，比如企鹅什么的，在你有空的时候并且有意愿的话也可以聊聊这方面的。

感觉网络蓝图确实不简单，集成动力的网络是存在WorldSavedData里的，要拷贝一整个网络估计问题会很多

**Comment by hanxiaoxin778** [comment]
> 你有Discord账号吗？QQ一般不在线

那算啦，我SSR炸了，上次下载IntegratedProxy一直构建不了项目... 所以才来问你要个deobf版，后来SSR又好了，然后就构建了一个deobf版.... 又炸了的..  阿里云的没办法。 

嗯，但集成动力实际上确实上手门槛比较高，有编程基础用起来可能没什么难度，但对一般的玩家来说确实太难了。这可能就是虽然MOD出来这么久了，但却在国内流行不起了来原因吧，国人能接受这个的还是比较少。所以一个拷贝功能可以让身边的小伙伴们也能参与进来一起玩，哈哈哈~ 而不是装了个MOD就感觉自己为自己装的。难也要做它XD

**Comment by shBLOCK** [comment]
提个小建议，这个巨型显示器的配方是不是有点太贵了，显示器本来就挺贵的了，要9个

**Comment by shBLOCK** [comment]
感觉在github的issue里说这些不太好，我QQ号：3332908658，尽量保持QQ在线，到时候把这个issue删了吧
