### ISSUE TITLE
Placing proxy against powered redstone writer and cable attached to the same network causes null pointer exception and execution exception. (1.12 confirmed/1.16 confirmed)

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#16]
https://user-images.githubusercontent.com/997239/122053904-cea63480-cdac-11eb-8936-dcc817e3bcea.mp4

[Notable Errors](https://hastebin.com/iqucolodew.php)
[Full Log](https://hastebin.com/evodovacot.properties)

The current workaround seems to be to place the proxy before the redstone writer.

Edit: [1.16 log](https://hastebin.com/dinanojubu.csharp)

Same steps to reproduce in 1.16.

**Comment by shBLOCK** [comment]
Will be fixed in the next release
