### ISSUE TITLE
Proxy connected to powered redstone writer and an interface ~~on the same proxy causes an exception and~~ on the same network causes exception log spam. (1.12 confirmed/1.16 confirmed)

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#17]
https://user-images.githubusercontent.com/997239/122056465-39f10600-cdaf-11eb-9b32-691f28dab497.mp4

Edit: I wasn't able to reproduce the exception being thrown on interface placement.
~~Each time a proxy is placed on this setup, a single exception will be written to the log.~~ If you are pointing a proxy to redstone dust; when you connect the redstone writer to the interface, it spams the log until the server/client crash or you're able to break a cable.

Setup: ![2021-06-15_08 11 08](https://user-images.githubusercontent.com/997239/122058578-5f7f0f00-cdb1-11eb-92e8-f0abe58c47a6.png)

When redstone dust is placed where the proxy is pointing, the spam should start.

[Snippet of exception](https://hastebin.com/eqijobijoc.md)

Edit: After stopping the spam by breaking the cable, if you then break the redstone writer [this](https://hastebin.com/ilohayajex.sql) error will be spammed until you break another component. After breaking another component, the server/client will crash with [exception in server tick loop](https://hastebin.com/junaxokaho.yaml).

Edit 2: [1.16 log](https://hastebin.com/morujocoxa.md) requires same steps to reproduce.

**Comment by shBLOCK** [comment]
Will be fixed in the next release
