### ISSUE TITLE
Redstone writer strong power option not working with proxy.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#2]
Minecraft: 1.12.2
Proxy Version: 1.0.1
Forge Version: 14.23.5.2854

![2021-06-09_19 24 23](https://user-images.githubusercontent.com/997239/121446804-fedb7680-c959-11eb-85f2-5aeb3d51e02b.png)

Expected: Block will be strongly powered and activate redstone components around it.

Actual: Block is not strongly powered.

Workaround: Placing redstone dust on the block the proxy is pointing to can make it almost work like a strongly powered block. This doesn't power the block above it while also powering the block beneath it however. It's not a complete replacement for the strongly powered option.

Also, thanks a lot for the great mod!

**Comment by shBLOCK** [comment]
Oh right, I forget the strong redstone thing, thank for reporting!

**Comment by shBLOCK** [comment]
Will be fixed in the next release
