### ISSUE TITLE
mine crash with simple modpach

### ISSUE THREAD

**Issue by ferreiraalex** [shBLOCK/IntegratedProxy#21]
mine crash with clear modpack
[crash-2021-07-01_07.30.39-client.txt](https://github.com/shBLOCK/IntegratedProxy/files/6745570/crash-2021-07-01_07.30.39-client.txt)

**Comment by shBLOCK** [comment]
Thanks for reporting!

**Comment by shBLOCK** [comment]
Hmm, can you boot the game with out this mod?

**Comment by ferreiraalex** [comment]
without your mod? yes i play now

**Comment by xemnes** [comment]
yup, getting the same exact crash, took me ages to figure out it was the newer update of this mod as it wasnt reporting any classes other than cyclops core.

**Comment by ferreiraalex** [comment]
> yup, getting the same exact crash, took me ages to figure out it was the newer update of this mod as it wasnt reporting any classes other than cyclops core.

i instantly see coz this mod use cyclops core and i add this mod and crash after first start

**Comment by shBLOCK** [comment]
Hmm, yep I can reproduce it now

**Comment by shBLOCK** [comment]
This is strange, might be a problem of my develop environment, just use 1.0.14 for now

**Comment by ferreiraalex** [comment]
Thanks! any help from me if need, and all respect to you for that mod! have a good progress its good mod! i will wait

**Comment by ferreiraalex** [comment]
close coz creator know about issue

**Comment by shBLOCK** [comment]
Oh right, I forgot to work on this for a long time, sorry about that, I'll work on it now, and I'll reopen this for a reminder

**Comment by ferreiraalex** [comment]
Hehe, okay i think you so much busy)

**Comment by shBLOCK** [comment]
This repo is not being maintained anymore, you can use [ForkedProxy](https://www.curseforge.com/minecraft/mc-mods/forked-proxy) for 1.12.2.
