### ISSUE TITLE
Block Properties not updating when using a Block Reader with a proxy

### ISSUE THREAD

**Issue by DraGonFiirE** [shBLOCK/IntegratedProxy#22]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Block Properties are not updating when using a Block Reader with a proxy

#### Steps to reproduce the problem:

1. Plant some seeds onto farmland
2. Set the proxy to the wheat seeds
3. Place the block reader pointing to the proxy
4. Take the `block` aspect and put it into the `block_props` function via the logic programmer
5. Put the `block` aspect into a variable store and put the block_props variable card into a display
6. You will see `age: "0"`
7. Grow the seeds with bonemeal
8. `age: 0` will not update despite the seeds clearly growing

#### Expected behaviour:

The variable card updating normally

____

#### Versions:

- Integrated_proxy-1.16-1.0.16
- IntegratedDynamics-1.16.5-1.9.0
- CyclopsCore-1.16.5-1.11.6
- CommonCapabilities-1.16.5-2.7.0
- Minecraft: 1.16.5
- Forge-1.16.5-36.1.16

Pulling the variable card out of the display and putting it back in updates it
Same thing with the `plant_age` function
Block properties have only recently been added by Integrated Dynamics

**Comment by shBLOCK** [comment]
Thanks for reporting!

**Comment by shBLOCK** [comment]
I think I just have to update the whole network when a block update trigger

**Comment by shBLOCK** [comment]
It's fixed, but if you use bonemeal to grow the crop, it won't trigger a CropGrowthEvent, so I can't detect it, this might be a forge issue.

**Comment by DraGonFiirE** [comment]
`Redstone Cage Latern` from Architect's Palette is not updating just yet which is the main thing why I orginally noticed this bug 
Vanilla `Redstone Lamp` has the exact same issue too, I just tested
Tested a few more vanilla blocks with blockstates and seems to me that the issue seems to be related to the blockstate `lit: true/false`

**Comment by shBLOCK** [comment]
Ok, I will test it

**Comment by shBLOCK** [comment]
Hmm, do you means this? It seems to be working on my test

https://user-images.githubusercontent.com/50770712/124672409-95fc0580-dee9-11eb-8556-04182e59778f.mp4

**Comment by DraGonFiirE** [comment]
you used Redstone Writer on your test, I meant the issue with the blockstates not updating like the first post
try to follow steps like the first post but instead of seeds use the redstone lamp and instead of bonemeal use a lever to switch between on and off and lookout for the blockstate `lit: true/false`

**Comment by shBLOCK** [comment]
It seems that the redstone lamp doesn't trigger a block update event (it will call a function in the nearby blocks, that's why it works with normal block reader):
![idea64_0kt2NEUOKV](https://user-images.githubusercontent.com/50770712/124706988-c9ab4f80-df2a-11eb-9df5-ae893d2d8e00.png)
So I can't do anything about this.

**Comment by shBLOCK** [comment]
one way to workaround this is to constantly update the block.
For example:
![java_vWCpH2rcKb](https://user-images.githubusercontent.com/50770712/124707569-91584100-df2b-11eb-9d5e-1f68ab73c591.png)
But it may cause lag

**Comment by DraGonFiirE** [comment]
> 
> 
> one way to workaround this is to constantly update the block.
> For example:
> ![java_vWCpH2rcKb](https://user-images.githubusercontent.com/50770712/124707569-91584100-df2b-11eb-9d5e-1f68ab73c591.png)
> But it may cause lag

this wont work, trying to figure out how to constantly update the ID network

**Comment by shBLOCK** [comment]
Oh right, if you are in a modpack, you can use a block breaker and a placer to place and break a cable again and again (just use a item pipe to transfer the cable item from breaker to placer) (some mod's block breaker won't get a cable item when break cable block)
