### ISSUE TITLE
Servercrash when updating to 1.0.17

### ISSUE THREAD

**Issue by DraGonFiirE** [shBLOCK/IntegratedProxy#23]
After updating my server to 1.0.17 it instantly crashes
[crash-2021-07-06_20.58.33-server.txt](https://github.com/shBLOCK/IntegratedProxy/files/6772827/crash-2021-07-06_20.58.33-server.txt)
[console error.txt](https://github.com/shBLOCK/IntegratedProxy/files/6772829/console.error.txt)
This gets displayed right before the crash in the server console

**Comment by shBLOCK** [comment]
Thanks for reporting!

**Comment by shBLOCK** [comment]
I posted version 1.0.18 on CurseForge, I'm not sure if it will fix the issue, try boot the server with 1.0.18.

**Comment by DraGonFiirE** [comment]
Seems like that fixed it, good job!

**Comment by DraGonFiirE** [comment]
nvm got a crash in singleplayer 
[crash-2021-07-07_19.39.26-server.txt](https://github.com/shBLOCK/IntegratedProxy/files/6779079/crash-2021-07-07_19.39.26-server.txt)

**Comment by shBLOCK** [comment]
What did you do that caused this crash?

**Comment by DraGonFiirE** [comment]
Sorry for not responding these couple of days, was busy
I'll make a new issue for it

**Comment by shBLOCK** [comment]
Okay
