### ISSUE TITLE
Servercrash when breaking logic cable

### ISSUE THREAD

**Issue by DraGonFiirE** [shBLOCK/IntegratedProxy#24]
https://user-images.githubusercontent.com/75578285/125199003-96d3c500-e264-11eb-9c95-cbea0a763621.mp4

[crash-2021-07-11_14.58.03-server.txt](https://github.com/shBLOCK/IntegratedProxy/files/6796950/crash-2021-07-11_14.58.03-server.txt)

**Comment by shBLOCK** [comment]
Hmm, the video seems to be broken, could you try send it again?

**Comment by DraGonFiirE** [comment]
Had to compress the video to get under the 10 mb size limit and now github doesnt accept it anymore <.<
https://streamable.com/st3tkw

**Comment by shBLOCK** [comment]
Fixed in 1.0.19
