### ISSUE TITLE
Crash with Cyclops Core mod

### ISSUE THREAD

**Issue by DrSigma4164** [shBLOCK/IntegratedProxy#26]
When I tried to insert a variable in cell x, I crashed minecraft. The log says that this is related to your mod as well as Cyclops Core
[crash-2022-01-14_13.33.07-server.txt](https://github.com/shBLOCK/IntegratedProxy/files/7870327/crash-2022-01-14_13.33.07-server.txt)

**Comment by shBLOCK** [comment]
Thanks for your report!
This is a problem that I should check for, but you should put a int type variable in the slot instead of a double one.

**Comment by DrSigma4164** [comment]
Tried to go into the world, and can not. Can you tell me how to fix it
[crash-2022-01-14_17.20.46-server.txt](https://github.com/shBLOCK/IntegratedProxy/files/7871381/crash-2022-01-14_17.20.46-server.txt)
?

**Comment by shBLOCK** [comment]
I will fix it with a new version

**Comment by shBLOCK** [comment]
Hmm, there seems to be some problem with my project, for now one solution is to delete that block using external tools like McEdit

**Comment by ComputerErika** [comment]
Wanted to second this because I got the same issue when I accidentally put a double in the x slot
The only way to fix was to remove the block using the Amulet Editor (MCEdit wouldn't load the world)
But otherwise, great mod! :D I love it.

**Comment by shBLOCK** [comment]
Sorry for thr issue though, I was having some issues with gradle when I was fixing the problem, and I kinda lost interest in this mod, so maybe I will deal with this when updating to newer version of minecraft (after ID is updated)

**Comment by shBLOCK** [comment]
It seems that this issue fixed itself when I was porting the mod to 1.18.
But lower version is still broken, I'm not sure if I will fix it for lower versions anymore, because a broken dev environment is just the most annoying thing...
