### ISSUE TITLE
Integrated Proxy null pointer exception when installed on server.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#3]
Integrated Proxy causes a null pointer exception in rendering for clients if using it on a server. Rendering error doesn't occur in single player as far as I can tell.

Reproduce: Can be reproduced with only Integrated Proxy, Integrated Dynamics and library mods. Make a new forge server with required mods. Connect to it using a client and attempt to open the config of a interface/reader/writer. The client will crash with null pointer exception in renderer.

Crash Log: [Hastebin](https://hastebin.com/pemukiwawo.csharp)

**Comment by shBLOCK** [comment]
Ok, thank for reporting!

**Comment by shBLOCK** [comment]
Will be fixed in the next release
