### ISSUE TITLE
Game Crash on initializing

### ISSUE THREAD

**Issue by 1Mangomaster1** [shBLOCK/IntegratedProxy#31]
Game instantly crashes once this mod was downloaded into my modpack

Here's the crash log
https://pastebin.com/tf9czDjq

Ik this is related to this mod because the pack worked fine until this mod was added, and once removed proceeded to work fine

**Comment by shBLOCK** [comment]
This repo is not being maintained anymore, you can use [ForkedProxy](https://www.curseforge.com/minecraft/mc-mods/forked-proxy) for 1.12.2.

**Comment by 1Mangomaster1** [comment]
Thank you
