### ISSUE TITLE
Writer/Reader error when using without integrated tunnels.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#4]
Sorry to continue posting issues. I wish I could help with pull requests but I don't have the knowledge. I have some slightly bad news and great news. Thank  you for your hard work and quick responses. 

With the library mods, Integrated Dynamics and Integrated Proxy, writers and readers don't work when connected to a server, even when a proxy isn't in the world. The server crashes with this configuration when you connect a redstone writer to a proxy then insert a variable card into the writer. The crash log for this is: [Haste](https://paste.dimdev.org/nenowilubi.mccrash}.

The great news though is that with Integrated Tunnels installed, everything seems to be working properly on a server ~~except for one issue which I'll create a new post for~~.  I'll have to test it more thoroughly on my main server, but as proof that it is working on my test server. ![2021-06-10_16 19 52](https://user-images.githubusercontent.com/997239/121598933-fd688780-ca07-11eb-9309-dcb40e56c444.png)

Edit: The other issue occurs in Integrated Dynamics without Proxy installed. If you change the strong power setting of a Redstone Writer from true to false, the redstone being powered by the strong powered block doesn't update to reflect the change until you cause a redstone update. This issue can be more clearly seen and abused using proxy since you can change the block proxy is pointing to, but it is not the cause.

![2021-06-10_16 20 44](https://user-images.githubusercontent.com/997239/121601776-052a2b00-ca0c-11eb-9349-fe33ebfa3913.png)
![2021-06-10_16 30 47](https://user-images.githubusercontent.com/997239/121601777-05c2c180-ca0c-11eb-8233-d0fad40ad698.png)
![2021-06-10_16 31 03](https://user-images.githubusercontent.com/997239/121601779-065b5800-ca0c-11eb-900a-e6be43241f9b.png)

**Comment by Icoza** [comment]
Just to reiterate, I can only reproduce this issue in a server that doesn't have Integrated Tunnels installed. This is a non-issue in single player without Tunnels or servers with Tunnels.

**Comment by shBLOCK** [comment]
No, continue posting issues is good! You are helping me find problems to fix!

**Comment by Icoza** [comment]
I must have had some other issue with the server when this issue occurred. I made a new server with Integrated Dynamics and Proxy without tunnels and it worked perfectly fine this time. I apologize for my mistake.

**Comment by Icoza** [comment]
This crash happens if the server or client is on Forge version 14.23.5.2854.
