### ISSUE TITLE
Changing the position a proxy is pointing to does not correctly update redstone when using a strong power redstone writer.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#5]
The first part of this issue is most likely caused by [Integrated Dynamics #1053](https://github.com/CyclopsMC/IntegratedDynamics/issues/1053}. However, changing the position a proxy is pointing to does not strong power the new position.

![2021-06-10_16 30 47](https://user-images.githubusercontent.com/997239/121605562-3b6aa900-ca12-11eb-9b75-739d27c6d2f5.png)

I originally strong powered the dirt block in the air, then changed the position to the dirt block on the ground. The redstone in both positions weren't updated to reflect this change until I provided a redstone/block update to both.

![2021-06-10_16 31 03](https://user-images.githubusercontent.com/997239/121606022-0ad73f00-ca13-11eb-8105-752032758614.png)

I'm not well versed in modding but how difficult and costly in terms of performance would it be to cause an update or redstone update on the block in the old position and new position when changing where the proxy is pointing? This issue does not occur when not using strong power.

Current workaround is to cause an update at the old and new position. The new position also starts working if you remove the variable card from the redstone writer and reinsert it.

Proxy version: 1.0.2
Minecraft version: 1.12.2
Forge version: 14.23.5.2855

**Comment by shBLOCK** [comment]
Yep, that's my problem, thank for reporting
