### ISSUE TITLE
Proxy causes exception in server tick loop when pointing at itself with redstone writer attached

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#6]
Closed one of my issues due to being incorrect. I apologize for my mistake.

Edit 2: Previous was all wrong, proxy causes a crash if you attach a redstone writer to a proxy that is pointing to itself no matter the Forge version. If you point the proxy at a different coordinate before attaching a redstone writer it works as expected. Gonna update after more testing.

Edit 3: 
The proxy above works as expected with no issues. However, the proxy in the bottom will crash my client in single player as soon as I put a variable card into the redstone writer to make it output power. 

[Crash Log](https://pastebin.com/wCN8j8ju)

![2021-06-10_21 50 04](https://user-images.githubusercontent.com/997239/121623914-2e5fb100-ca36-11eb-94dd-b52ef95aeb05.png)
![2021-06-10_21 50 06](https://user-images.githubusercontent.com/997239/121623916-2f90de00-ca36-11eb-898a-591feba55b10.png)

~~The crash is caused by not using Forge version 14.23.5.2855 on either server or client on Minecraft 1.12.2.  I posted this issue to bring it to your attention but there isn't anything to fix. If it would be possible to also make it work on 2854 it would nice but I'm not sure how difficult that would be. The reason I say this is because some mods suggest users stay on Forge 2854 due to issues the latest release causes in their mods. Here is a log if it can help with 2854 compatibility. Client CrashLog: [Paste](https://pastebin.com/mP1q0Gjd) Server Log when error occurs: [Server Paste](https://pastebin.com/rpSnEjPg) 
[Full Server Log](https://github.com/shBLOCK/IntegratedProxy/files/6635167/message.txt)
The issue causes all readers/writers to stop working on a server and causes crashes in single player. You can delete  issue #4. Thank you again.~~

~~Edit: Messed with it some more, Forge versions before 2855 crash or cause errors only when you attach a redstone writer to a proxy.~~

**Comment by shBLOCK** [comment]
Ok, thank for help testing my mod!
