### ISSUE TITLE
新开存档放下代理器就未响应

### ISSUE THREAD

**Issue by WildMeowGames** [shBLOCK/IntegratedProxy#7]
错误日志：
![1](https://user-images.githubusercontent.com/56909786/121733122-a8229800-cb25-11eb-9677-9d47e503309d.jpg)

MOD版本1.0.4
这次更新之后好像跟某些MOD起冲突了，新开存档，代理器刚放下去的一瞬间游戏就未响应。

以下为MOD列表，在1.0.2版本中可以正常使用。
![QQ截图20210612021145](https://user-images.githubusercontent.com/56909786/121731459-8de7ba80-cb23-11eb-8406-426294634d32.jpg)

**Comment by shBLOCK** [comment]
额，忘了设置默认值了，对不起
我会很快修复

**Comment by shBLOCK** [comment]
点错了...

**Comment by WildMeowGames** [comment]
> 点错了...

没关系的，辛苦了，假期还要码码码！

**Comment by shBLOCK** [comment]
正在弄1.16的远程红石功能，现在暂时无法编译，所以稍等一会

**Comment by WildMeowGames** [comment]
> 正在弄1.16的远程红石功能，现在暂时无法编译，所以稍等一会

好的好的！辛苦啦！之后close掉我就去 curseforge 提货 XD

**Comment by shBLOCK** [comment]
已在1.0.5修复，curseforge需要审核一下，很快就有了
但是注意一下，现在太快地更改位置可能会导致很大卡顿，正在想办法修复

**Comment by WildMeowGames** [comment]
> 已在1.0.5修复，curseforge需要审核一下，很快就有了
> 但是注意一下，现在太快地更改位置可能会导致很大卡顿，正在想办法修复

好的，感谢大大！
