### ISSUE TITLE
Redstone not updated upon breaking proxy block.

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#8]
I was able to reproduce this on both 1.12 and 1.16. Breaking the proxy while having a redstone writer powering redstone through it will cause the redstone to remain powered until an update happens to it. You have to break the proxy first.

![2021-06-12_07 21 23](https://user-images.githubusercontent.com/997239/121776760-44639380-cb54-11eb-9974-e8f8979c8b0f.png)
![2021-06-12_07 21 32](https://user-images.githubusercontent.com/997239/121776761-44fc2a00-cb54-11eb-9a54-fb45fa1a38d5.png)
![2021-06-12_07 57 52](https://user-images.githubusercontent.com/997239/121776768-50e7ec00-cb54-11eb-8418-4ff86fee3582.png)

**Comment by shBLOCK** [comment]
Oh yea, I shouold do an update when the block break

**Comment by Icoza** [comment]
Working with redstone in game is a huge pain, I wouldn't even want to imagine how painful it is in the code base.

**Comment by shBLOCK** [comment]
Ugh, the problem is solved, but my network is being a little funny about github, I can't push the changes...
