### ISSUE TITLE
Breaking proxy by hand/tool other than wrench while a reader/writer is attached causes exception in server tick

### ISSUE THREAD

**Issue by Icoza** [shBLOCK/IntegratedProxy#9]
I can only reproduce this issue in 1.16, but breaking a proxy by means other than Integrated Wrench causes exception in server tick loop. [Crash Log](https://hastebin.com/qaquvagoga.properties). I was able to cause this crash breaking by hand and with a pickaxe.

**Comment by shBLOCK** [comment]
Thank for helping me test the mod!

**Comment by shBLOCK** [comment]
Oh, yea, try install the IntegratedTunnels mod in your Minecraft instance, that should solve it for now, I'll solve this bug soon

**Comment by Icoza** [comment]
You're right, with Tunnels installed I can't reproduce the crash anymore. I can't think of many cases where Dynamics would be installed without Tunnels.

**Comment by shBLOCK** [comment]
I'll probably fix this tomorrow, my network is soo unstable right now

**Comment by Icoza** [comment]
Sounds good to me, probably not a very common case where one is installed without the other. Only reason I found it is because I'm testing a lot of weird edge cases right now.

**Comment by Icoza** [comment]
Similar issue happens in 1.12 without Integrated Tunnels just so you know. It doesn't appear to cause a crash, but it does leave an invisible proxy until you break the readers/writers that were attached. I doubt many users would have Dynamics without Tunnels though. 🤷‍♂️
![2021-06-12_09 06 14](https://user-images.githubusercontent.com/997239/121778651-7c230900-cb5d-11eb-8596-7826960f37b8.png)
![2021-06-12_09 06 19](https://user-images.githubusercontent.com/997239/121778652-7cbb9f80-cb5d-11eb-8552-6ce1e55fb024.png)
![2021-06-12_09 06 23](https://user-images.githubusercontent.com/997239/121778655-7cbb9f80-cb5d-11eb-9f3b-283ff52c7e2a.png)

**Comment by shBLOCK** [comment]
This is not hard to fix, the cause of this issue is because I recently made the WorldBlockImporter don't break the proxy block, so that is you variable have a problem, the proxy block won't be broke, so I have to check if the player that's breaking the block is the FakePlayer from IntegratedTunnels, if it is, don't allow the fake player to break it, but if you don't have IntegratedTunnels installed, it can't find the FakePlayer class, so it just crash
